// GENERATED FILE. Do not edit by hand.
// Run "npm run generate-mock-globe" to rebuild it from scripts/demo-dataset.ts.
//
// The landing hero's static fallback: a snapshot of the public demo account's
// completed and ongoing trips, rendered when the live anon read of that account
// is unavailable. Planned trips are excluded, matching the live hero. Every
// coordinate here is a real place, carried over from the seed fixture.
//
// Trips in this snapshot:
//   2019  Interrail Summer
//   2021  Dia de Muertos Long Weekend
//   2022  Slow Loop Through Southeast Asia
//   2023  Andes Adventure
//   2024  Golden Week in Japan
//   2024  Serengeti and the Swahili Coast
//   2025  Down Under and Across the Ditch
//   2026  Iceland Ring Road
//   2026  Fjords and Midnight Sun

import type { GlobeArc, GlobeDestination } from "@/components/map/globe-types";

/** ISO 3166-1 alpha-2 codes, matched against ISO_A2_EH in countries.geojson. */
const visitedCountryCodes: string[] = ["AR","AT","AU","BO","CZ","DE","HU","IS","JP","KE","KH","LA","MX","NL","NO","NZ","PE","TH","TZ","VN"];

const destinations: GlobeDestination[] = [
  {
    id: "dest-interrail-summer-amsterdam",
    tripId: "trip-interrail-summer",
    tripName: "Interrail Summer",
    name: "Amsterdam",
    countryCode: "NL",
    lat: 52.3676,
    lng: 4.9041,
    categoryColor: "#6366F1",
  },
  {
    id: "dest-interrail-summer-berlin",
    tripId: "trip-interrail-summer",
    tripName: "Interrail Summer",
    name: "Berlin",
    countryCode: "DE",
    lat: 52.52,
    lng: 13.405,
    categoryColor: "#3B82F6",
  },
  {
    id: "dest-interrail-summer-prague",
    tripId: "trip-interrail-summer",
    tripName: "Interrail Summer",
    name: "Prague",
    countryCode: "CZ",
    lat: 50.0755,
    lng: 14.4378,
    categoryColor: "#14B8A6",
  },
  {
    id: "dest-interrail-summer-vienna",
    tripId: "trip-interrail-summer",
    tripName: "Interrail Summer",
    name: "Vienna",
    countryCode: "AT",
    lat: 48.2082,
    lng: 16.3738,
    categoryColor: "#F59E0B",
  },
  {
    id: "dest-interrail-summer-budapest",
    tripId: "trip-interrail-summer",
    tripName: "Interrail Summer",
    name: "Budapest",
    countryCode: "HU",
    lat: 47.4979,
    lng: 19.0402,
    categoryColor: "#14B8A6",
  },
  {
    id: "dest-dia-de-muertos-long-weekend-mexico-city",
    tripId: "trip-dia-de-muertos-long-weekend",
    tripName: "Dia de Muertos Long Weekend",
    name: "Mexico City",
    countryCode: "MX",
    lat: 19.4326,
    lng: -99.1332,
    categoryColor: "#6366F1",
  },
  {
    id: "dest-dia-de-muertos-long-weekend-puebla",
    tripId: "trip-dia-de-muertos-long-weekend",
    tripName: "Dia de Muertos Long Weekend",
    name: "Puebla",
    countryCode: "MX",
    lat: 19.0414,
    lng: -98.2063,
    categoryColor: "#2563EB",
  },
  {
    id: "dest-dia-de-muertos-long-weekend-oaxaca",
    tripId: "trip-dia-de-muertos-long-weekend",
    tripName: "Dia de Muertos Long Weekend",
    name: "Oaxaca",
    countryCode: "MX",
    lat: 17.0732,
    lng: -96.7266,
    categoryColor: "#F59E0B",
  },
  {
    id: "dest-slow-loop-through-southeast-asia-bangkok",
    tripId: "trip-slow-loop-through-southeast-asia",
    tripName: "Slow Loop Through Southeast Asia",
    name: "Bangkok",
    countryCode: "TH",
    lat: 13.7563,
    lng: 100.5018,
    categoryColor: "#2563EB",
  },
  {
    id: "dest-slow-loop-through-southeast-asia-chiang-mai",
    tripId: "trip-slow-loop-through-southeast-asia",
    tripName: "Slow Loop Through Southeast Asia",
    name: "Chiang Mai",
    countryCode: "TH",
    lat: 18.7883,
    lng: 98.9853,
    categoryColor: "#10B981",
  },
  {
    id: "dest-slow-loop-through-southeast-asia-luang-prabang",
    tripId: "trip-slow-loop-through-southeast-asia",
    tripName: "Slow Loop Through Southeast Asia",
    name: "Luang Prabang",
    countryCode: "LA",
    lat: 19.8834,
    lng: 102.1347,
    categoryColor: "#10B981",
  },
  {
    id: "dest-slow-loop-through-southeast-asia-hanoi",
    tripId: "trip-slow-loop-through-southeast-asia",
    tripName: "Slow Loop Through Southeast Asia",
    name: "Hanoi",
    countryCode: "VN",
    lat: 21.0278,
    lng: 105.8342,
    categoryColor: "#3B82F6",
  },
  {
    id: "dest-slow-loop-through-southeast-asia-siem-reap",
    tripId: "trip-slow-loop-through-southeast-asia",
    tripName: "Slow Loop Through Southeast Asia",
    name: "Siem Reap",
    countryCode: "KH",
    lat: 13.3671,
    lng: 103.8448,
    categoryColor: "#2563EB",
  },
  {
    id: "dest-andes-adventure-lima",
    tripId: "trip-andes-adventure",
    tripName: "Andes Adventure",
    name: "Lima",
    countryCode: "PE",
    lat: -12.0464,
    lng: -77.0428,
    categoryColor: "#3B82F6",
  },
  {
    id: "dest-andes-adventure-cusco",
    tripId: "trip-andes-adventure",
    tripName: "Andes Adventure",
    name: "Cusco",
    countryCode: "PE",
    lat: -13.5319,
    lng: -71.9675,
    categoryColor: "#2563EB",
  },
  {
    id: "dest-andes-adventure-la-paz",
    tripId: "trip-andes-adventure",
    tripName: "Andes Adventure",
    name: "La Paz",
    countryCode: "BO",
    lat: -16.4897,
    lng: -68.1193,
    categoryColor: "#94A3B8",
  },
  {
    id: "dest-andes-adventure-uyuni",
    tripId: "trip-andes-adventure",
    tripName: "Andes Adventure",
    name: "Uyuni",
    countryCode: "BO",
    lat: -20.4597,
    lng: -66.825,
    categoryColor: "#10B981",
  },
  {
    id: "dest-andes-adventure-buenos-aires",
    tripId: "trip-andes-adventure",
    tripName: "Andes Adventure",
    name: "Buenos Aires",
    countryCode: "AR",
    lat: -34.6037,
    lng: -58.3816,
    categoryColor: "#3B82F6",
  },
  {
    id: "dest-golden-week-in-japan-tokyo",
    tripId: "trip-golden-week-in-japan",
    tripName: "Golden Week in Japan",
    name: "Tokyo",
    countryCode: "JP",
    lat: 35.6762,
    lng: 139.6503,
    categoryColor: "#14B8A6",
  },
  {
    id: "dest-golden-week-in-japan-hakone",
    tripId: "trip-golden-week-in-japan",
    tripName: "Golden Week in Japan",
    name: "Hakone",
    countryCode: "JP",
    lat: 35.2324,
    lng: 139.1069,
    categoryColor: "#64748B",
  },
  {
    id: "dest-golden-week-in-japan-kanazawa",
    tripId: "trip-golden-week-in-japan",
    tripName: "Golden Week in Japan",
    name: "Kanazawa",
    countryCode: "JP",
    lat: 36.5613,
    lng: 136.6562,
    categoryColor: "#10B981",
  },
  {
    id: "dest-golden-week-in-japan-kyoto",
    tripId: "trip-golden-week-in-japan",
    tripName: "Golden Week in Japan",
    name: "Kyoto",
    countryCode: "JP",
    lat: 35.0116,
    lng: 135.7681,
    categoryColor: "#2563EB",
  },
  {
    id: "dest-golden-week-in-japan-osaka",
    tripId: "trip-golden-week-in-japan",
    tripName: "Golden Week in Japan",
    name: "Osaka",
    countryCode: "JP",
    lat: 34.6937,
    lng: 135.5023,
    categoryColor: "#A855F7",
  },
  {
    id: "dest-serengeti-and-the-swahili-coast-nairobi",
    tripId: "trip-serengeti-and-the-swahili-coast",
    tripName: "Serengeti and the Swahili Coast",
    name: "Nairobi",
    countryCode: "KE",
    lat: -1.2921,
    lng: 36.8219,
    categoryColor: "#10B981",
  },
  {
    id: "dest-serengeti-and-the-swahili-coast-arusha",
    tripId: "trip-serengeti-and-the-swahili-coast",
    tripName: "Serengeti and the Swahili Coast",
    name: "Arusha",
    countryCode: "TZ",
    lat: -3.3869,
    lng: 36.683,
    categoryColor: "#14B8A6",
  },
  {
    id: "dest-serengeti-and-the-swahili-coast-serengeti-national-park",
    tripId: "trip-serengeti-and-the-swahili-coast",
    tripName: "Serengeti and the Swahili Coast",
    name: "Serengeti National Park",
    countryCode: "TZ",
    lat: -2.3333,
    lng: 34.8333,
    categoryColor: "#10B981",
  },
  {
    id: "dest-serengeti-and-the-swahili-coast-stone-town",
    tripId: "trip-serengeti-and-the-swahili-coast",
    tripName: "Serengeti and the Swahili Coast",
    name: "Stone Town",
    countryCode: "TZ",
    lat: -6.1659,
    lng: 39.1917,
    categoryColor: "#06B6D4",
  },
  {
    id: "dest-down-under-and-across-the-ditch-sydney",
    tripId: "trip-down-under-and-across-the-ditch",
    tripName: "Down Under and Across the Ditch",
    name: "Sydney",
    countryCode: "AU",
    lat: -33.8688,
    lng: 151.2093,
    categoryColor: "#10B981",
  },
  {
    id: "dest-down-under-and-across-the-ditch-melbourne",
    tripId: "trip-down-under-and-across-the-ditch",
    tripName: "Down Under and Across the Ditch",
    name: "Melbourne",
    countryCode: "AU",
    lat: -37.8136,
    lng: 144.9631,
    categoryColor: "#3B82F6",
  },
  {
    id: "dest-down-under-and-across-the-ditch-queenstown",
    tripId: "trip-down-under-and-across-the-ditch",
    tripName: "Down Under and Across the Ditch",
    name: "Queenstown",
    countryCode: "NZ",
    lat: -45.0312,
    lng: 168.6626,
    categoryColor: "#F59E0B",
  },
  {
    id: "dest-down-under-and-across-the-ditch-rotorua",
    tripId: "trip-down-under-and-across-the-ditch",
    tripName: "Down Under and Across the Ditch",
    name: "Rotorua",
    countryCode: "NZ",
    lat: -38.1368,
    lng: 176.2497,
    categoryColor: "#F59E0B",
  },
  {
    id: "dest-down-under-and-across-the-ditch-auckland",
    tripId: "trip-down-under-and-across-the-ditch",
    tripName: "Down Under and Across the Ditch",
    name: "Auckland",
    countryCode: "NZ",
    lat: -36.8485,
    lng: 174.7633,
    categoryColor: "#F59E0B",
  },
  {
    id: "dest-iceland-ring-road-reykjavik",
    tripId: "trip-iceland-ring-road",
    tripName: "Iceland Ring Road",
    name: "Reykjavik",
    countryCode: "IS",
    lat: 64.1466,
    lng: -21.9426,
    categoryColor: "#F59E0B",
  },
  {
    id: "dest-iceland-ring-road-vik",
    tripId: "trip-iceland-ring-road",
    tripName: "Iceland Ring Road",
    name: "Vik",
    countryCode: "IS",
    lat: 63.4187,
    lng: -19.006,
    categoryColor: "#10B981",
  },
  {
    id: "dest-iceland-ring-road-hofn",
    tripId: "trip-iceland-ring-road",
    tripName: "Iceland Ring Road",
    name: "Hofn",
    countryCode: "IS",
    lat: 64.2539,
    lng: -15.2082,
    categoryColor: "#10B981",
  },
  {
    id: "dest-iceland-ring-road-akureyri",
    tripId: "trip-iceland-ring-road",
    tripName: "Iceland Ring Road",
    name: "Akureyri",
    countryCode: "IS",
    lat: 65.6835,
    lng: -18.0878,
    categoryColor: "#10B981",
  },
  {
    id: "dest-fjords-and-midnight-sun-oslo",
    tripId: "trip-fjords-and-midnight-sun",
    tripName: "Fjords and Midnight Sun",
    name: "Oslo",
    countryCode: "NO",
    lat: 59.9139,
    lng: 10.7522,
    categoryColor: "#6366F1",
  },
  {
    id: "dest-fjords-and-midnight-sun-bergen",
    tripId: "trip-fjords-and-midnight-sun",
    tripName: "Fjords and Midnight Sun",
    name: "Bergen",
    countryCode: "NO",
    lat: 60.3913,
    lng: 5.3221,
    categoryColor: "#14B8A6",
  },
  {
    id: "dest-fjords-and-midnight-sun-flam",
    tripId: "trip-fjords-and-midnight-sun",
    tripName: "Fjords and Midnight Sun",
    name: "Flam",
    countryCode: "NO",
    lat: 60.8631,
    lng: 7.1136,
    categoryColor: "#94A3B8",
  },
  {
    id: "dest-fjords-and-midnight-sun-tromso",
    tripId: "trip-fjords-and-midnight-sun",
    tripName: "Fjords and Midnight Sun",
    name: "Tromso",
    countryCode: "NO",
    lat: 69.6492,
    lng: 18.9553,
    categoryColor: null,
  },
].map((destination) => ({
  ...destination,
  arrivalDate: null,
  departureDate: null,
}));

const arcs: GlobeArc[] = [
  {
    sourcePosition: [4.9041, 52.3676],
    targetPosition: [13.405, 52.52],
    tripName: "Interrail Summer",
    sourceCity: "Amsterdam",
    targetCity: "Berlin",
  },
  {
    sourcePosition: [13.405, 52.52],
    targetPosition: [14.4378, 50.0755],
    tripName: "Interrail Summer",
    sourceCity: "Berlin",
    targetCity: "Prague",
  },
  {
    sourcePosition: [14.4378, 50.0755],
    targetPosition: [16.3738, 48.2082],
    tripName: "Interrail Summer",
    sourceCity: "Prague",
    targetCity: "Vienna",
  },
  {
    sourcePosition: [16.3738, 48.2082],
    targetPosition: [19.0402, 47.4979],
    tripName: "Interrail Summer",
    sourceCity: "Vienna",
    targetCity: "Budapest",
  },
  {
    sourcePosition: [-99.1332, 19.4326],
    targetPosition: [-98.2063, 19.0414],
    tripName: "Dia de Muertos Long Weekend",
    sourceCity: "Mexico City",
    targetCity: "Puebla",
  },
  {
    sourcePosition: [-98.2063, 19.0414],
    targetPosition: [-96.7266, 17.0732],
    tripName: "Dia de Muertos Long Weekend",
    sourceCity: "Puebla",
    targetCity: "Oaxaca",
  },
  {
    sourcePosition: [100.5018, 13.7563],
    targetPosition: [98.9853, 18.7883],
    tripName: "Slow Loop Through Southeast Asia",
    sourceCity: "Bangkok",
    targetCity: "Chiang Mai",
  },
  {
    sourcePosition: [98.9853, 18.7883],
    targetPosition: [102.1347, 19.8834],
    tripName: "Slow Loop Through Southeast Asia",
    sourceCity: "Chiang Mai",
    targetCity: "Luang Prabang",
  },
  {
    sourcePosition: [102.1347, 19.8834],
    targetPosition: [105.8342, 21.0278],
    tripName: "Slow Loop Through Southeast Asia",
    sourceCity: "Luang Prabang",
    targetCity: "Hanoi",
  },
  {
    sourcePosition: [105.8342, 21.0278],
    targetPosition: [103.8448, 13.3671],
    tripName: "Slow Loop Through Southeast Asia",
    sourceCity: "Hanoi",
    targetCity: "Siem Reap",
  },
  {
    sourcePosition: [-77.0428, -12.0464],
    targetPosition: [-71.9675, -13.5319],
    tripName: "Andes Adventure",
    sourceCity: "Lima",
    targetCity: "Cusco",
  },
  {
    sourcePosition: [-71.9675, -13.5319],
    targetPosition: [-68.1193, -16.4897],
    tripName: "Andes Adventure",
    sourceCity: "Cusco",
    targetCity: "La Paz",
  },
  {
    sourcePosition: [-68.1193, -16.4897],
    targetPosition: [-66.825, -20.4597],
    tripName: "Andes Adventure",
    sourceCity: "La Paz",
    targetCity: "Uyuni",
  },
  {
    sourcePosition: [-66.825, -20.4597],
    targetPosition: [-58.3816, -34.6037],
    tripName: "Andes Adventure",
    sourceCity: "Uyuni",
    targetCity: "Buenos Aires",
  },
  {
    sourcePosition: [139.6503, 35.6762],
    targetPosition: [139.1069, 35.2324],
    tripName: "Golden Week in Japan",
    sourceCity: "Tokyo",
    targetCity: "Hakone",
  },
  {
    sourcePosition: [139.1069, 35.2324],
    targetPosition: [136.6562, 36.5613],
    tripName: "Golden Week in Japan",
    sourceCity: "Hakone",
    targetCity: "Kanazawa",
  },
  {
    sourcePosition: [136.6562, 36.5613],
    targetPosition: [135.7681, 35.0116],
    tripName: "Golden Week in Japan",
    sourceCity: "Kanazawa",
    targetCity: "Kyoto",
  },
  {
    sourcePosition: [135.7681, 35.0116],
    targetPosition: [135.5023, 34.6937],
    tripName: "Golden Week in Japan",
    sourceCity: "Kyoto",
    targetCity: "Osaka",
  },
  {
    sourcePosition: [36.8219, -1.2921],
    targetPosition: [36.683, -3.3869],
    tripName: "Serengeti and the Swahili Coast",
    sourceCity: "Nairobi",
    targetCity: "Arusha",
  },
  {
    sourcePosition: [36.683, -3.3869],
    targetPosition: [34.8333, -2.3333],
    tripName: "Serengeti and the Swahili Coast",
    sourceCity: "Arusha",
    targetCity: "Serengeti National Park",
  },
  {
    sourcePosition: [34.8333, -2.3333],
    targetPosition: [39.1917, -6.1659],
    tripName: "Serengeti and the Swahili Coast",
    sourceCity: "Serengeti National Park",
    targetCity: "Stone Town",
  },
  {
    sourcePosition: [151.2093, -33.8688],
    targetPosition: [144.9631, -37.8136],
    tripName: "Down Under and Across the Ditch",
    sourceCity: "Sydney",
    targetCity: "Melbourne",
  },
  {
    sourcePosition: [144.9631, -37.8136],
    targetPosition: [168.6626, -45.0312],
    tripName: "Down Under and Across the Ditch",
    sourceCity: "Melbourne",
    targetCity: "Queenstown",
  },
  {
    sourcePosition: [168.6626, -45.0312],
    targetPosition: [176.2497, -38.1368],
    tripName: "Down Under and Across the Ditch",
    sourceCity: "Queenstown",
    targetCity: "Rotorua",
  },
  {
    sourcePosition: [176.2497, -38.1368],
    targetPosition: [174.7633, -36.8485],
    tripName: "Down Under and Across the Ditch",
    sourceCity: "Rotorua",
    targetCity: "Auckland",
  },
  {
    sourcePosition: [-21.9426, 64.1466],
    targetPosition: [-19.006, 63.4187],
    tripName: "Iceland Ring Road",
    sourceCity: "Reykjavik",
    targetCity: "Vik",
  },
  {
    sourcePosition: [-19.006, 63.4187],
    targetPosition: [-15.2082, 64.2539],
    tripName: "Iceland Ring Road",
    sourceCity: "Vik",
    targetCity: "Hofn",
  },
  {
    sourcePosition: [-15.2082, 64.2539],
    targetPosition: [-18.0878, 65.6835],
    tripName: "Iceland Ring Road",
    sourceCity: "Hofn",
    targetCity: "Akureyri",
  },
  {
    sourcePosition: [10.7522, 59.9139],
    targetPosition: [5.3221, 60.3913],
    tripName: "Fjords and Midnight Sun",
    sourceCity: "Oslo",
    targetCity: "Bergen",
  },
  {
    sourcePosition: [5.3221, 60.3913],
    targetPosition: [7.1136, 60.8631],
    tripName: "Fjords and Midnight Sun",
    sourceCity: "Bergen",
    targetCity: "Flam",
  },
  {
    sourcePosition: [7.1136, 60.8631],
    targetPosition: [18.9553, 69.6492],
    tripName: "Fjords and Midnight Sun",
    sourceCity: "Flam",
    targetCity: "Tromso",
  },
];

/**
 * The fallback globe payload, in the same shape the live landing read returns.
 */
export function buildMockGlobeProps(): {
  visitedCountryCodes: string[];
  destinations: GlobeDestination[];
  arcs: GlobeArc[];
} {
  return { visitedCountryCodes, destinations, arcs };
}
